/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import entities.Client;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ClientService;
import service.CategorieService;
import service.ChambreService;
import entities.Chambre;
   import entities.Categorie;   
 import entities.Reservation; 
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import service.ReservationService;

/**
 *
 * @author Souloh
 */
public class ReservationForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientForm
     */
         private static int id; 
          Connection con;
         
    ReservationService reservation =new ReservationService();

    ClientService client =new ClientService();
    ChambreService chambre=new ChambreService();   
    private DefaultTableModel mode2;
    public ReservationForm() {
        initComponents();
         this.loadChambre();
         this.loadClient();
         mode2=(DefaultTableModel) ListeReservation.getModel();
         load();
        
          
          
          
          
    }
    private void loadChambre(){
    
     for(Chambre c:chambre.findAll()){
        ListeChambre.addItem(c);
     }
        
    }
     private void loadClient(){
    
     for(Client c:client.findAll()){
        ListeClient.addItem(c);
     }
        
    }
    private void load(){
         mode2.setRowCount(0);
        for (Reservation c: reservation.findAll()){
            mode2.addRow(new Object[]{
            c.getId(),
                   c.getClient().getNom(),
            c.getChambre().getTelephone(),
         
            c.getDatedebut(),
              c.getDatefin(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListeClient = new javax.swing.JComboBox();
        ListeChambre = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeReservation = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nom Client");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Telephone Chambre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date Debut");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date Fin");

        ListeReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom Client", "Telephone Chambre", "Date début", "Date fin"
            }
        ));
        ListeReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeReservation);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ID");

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton3.setText("Find");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton5.setText("Find All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 153, 255));
        jButton6.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton6.setText("Download PDF");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 153, 255));
        jButton7.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        jButton7.setText("Find  between two dates");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(ListeClient, 0, 155, Short.MAX_VALUE)
                        .addComponent(ListeChambre, 0, 155, Short.MAX_VALUE)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ListeChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jButton5))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Chambre chambre =(Chambre) ListeChambre.getSelectedItem();
       Client client =(Client) ListeClient.getSelectedItem();
       //Date.parse(jDateChooser2.getDateFormatString("yyyy-MM-dd"))
      
      Date dateDebut = jDateChooser2.getDate();
        Date dateFin = jDateChooser3.getDate();
        if(dateFin.compareTo(dateDebut)<=0){
            JOptionPane.showMessageDialog(this, "Vous devez donner la date de depard plus ancienne que la date de fin");
        return;
        }
        if(reservation.create(new Reservation(chambre,client,new Date(dateDebut.getTime()),new Date(dateFin.getTime())))){
            
            JOptionPane.showMessageDialog(this, "Reservation bien ajouter");
            load();  
        }else {
            JOptionPane.showMessageDialog(this, "Reservation non ajouter");
            load();  
              }
        
         
        
                            



       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListeReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeReservationMouseClicked
 this.id=(int)mode2.getValueAt(ListeReservation.getSelectedRow(), 0);
        
                 
           ListeClient.getModel().setSelectedItem( mode2.getValueAt(ListeReservation.getSelectedRow(),1));
jDateChooser2.setDate((Date)mode2.getValueAt(ListeReservation.getSelectedRow(), 3));
        jDateChooser3.setDate((Date)mode2.getValueAt(ListeReservation.getSelectedRow(), 4)); 
           ListeChambre.getModel().setSelectedItem( mode2.getValueAt(ListeReservation.getSelectedRow(),2));
                        



// TODO add your handling code here:
    }//GEN-LAST:event_ListeReservationMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int reponse=JOptionPane.showConfirmDialog(this, "T'es sure de supprimer la reservation");
if(reponse==0){
    this.reservation.delete(this.reservation.findById(id));
JOptionPane.showMessageDialog(this, "Reservation bien supprimer");
load();        // TODO add your handling code here:
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Chambre chambre =(Chambre) ListeChambre.getSelectedItem();
       Client client =(Client) ListeClient.getSelectedItem();
       //Date.parse(jDateChooser2.getDateFormatString("yyyy-MM-dd"))
      
      Date dateDebut = jDateChooser2.getDate();
        Date dateFin = jDateChooser3.getDate();
        if(dateFin.compareTo(dateDebut)<=0){
            JOptionPane.showMessageDialog(this, "Vous devez donner la date de depard plus ancienne que la date de fin");
        return;
        }
        int reponse=JOptionPane.showConfirmDialog(this, "T'es sure de modifier la reservation");
if(reponse==0){

   reservation.update(new Reservation(id,chambre,client, dateDebut, dateFin));
JOptionPane.showMessageDialog(this, "Reservation bien modifier");
load();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id=Integer.parseInt(jTextField5.getText());
        mode2.setRowCount(0);
        Reservation c=reservation.findById(id);

        mode2.addRow(new Object[]{
            c.getId(),
                   c.getClient().getNom(),
            c.getChambre().getTelephone(),
         
            c.getDatedebut(),
              c.getDatefin(),
            });
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        load();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
// Définit son contenu à imprimer
job.setPrintable(ListeReservation.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null));// Affiche une boîte de choix d'imprimante
if (job.printDialog()) {
     try {
        // Effectue l'impression
        job.print();
      } catch (PrinterException ex) {
       ex.printStackTrace();
     }
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
   PrinterJob job = PrinterJob.getPrinterJob();
// Définit son contenu à imprimer
job.setPrintable(ListeReservation.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null));// Affiche une boîte de choix d'imprimante
if (job.printDialog()) {
     try {
        // Effectue l'impression
        job.print();
      } catch (PrinterException ex) {
       ex.printStackTrace();
     }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
 Date dateDebut = jDateChooser2.getDate();
        Date dateFin = jDateChooser3.getDate();
       Client client =(Client) ListeClient.getSelectedItem();
        
        mode2.setRowCount(0);
        for (Reservation c: reservation.findChambreBetweenDates(dateDebut,dateFin,client)){
            mode2.addRow(new Object[]{
            c.getId(),
                   c.getClient().getNom(),
            c.getChambre().getTelephone(),
         
            c.getDatedebut(),
              c.getDatefin(),
            });
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     int id=Integer.parseInt(jTextField5.getText());
        mode2.setRowCount(0);
        Reservation c=reservation.findById(id);

        mode2.addRow(new Object[]{
            c.getId(),
                   c.getClient().getNom(),
            c.getChambre().getTelephone(),
         
            c.getDatedebut(),
              c.getDatefin(),
            });        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    Chambre chambre =(Chambre) ListeChambre.getSelectedItem();
       Client client =(Client) ListeClient.getSelectedItem();
       //Date.parse(jDateChooser2.getDateFormatString("yyyy-MM-dd"))
      
      Date dateDebut = jDateChooser2.getDate();
        Date dateFin = jDateChooser3.getDate();
        if(dateFin.compareTo(dateDebut)<=0){
            JOptionPane.showMessageDialog(this, "Vous devez donner la date de depard plus ancienne que la date de fin");
        return;
        }
        if(reservation.create(new Reservation(chambre,client,new Date(dateDebut.getTime()),new Date(dateFin.getTime())))){
            
            JOptionPane.showMessageDialog(this, "Reservation bien ajouter");
            load();  
        }else {
            JOptionPane.showMessageDialog(this, "Reservation non ajouter");
            load();  
              }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ListeChambre;
    private javax.swing.JComboBox ListeClient;
    private javax.swing.JTable ListeReservation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
